language: node_js
node_js:
- '10'
deploy:
  provider: heroku
  app: koa-node-chat
  api_key:
    secure: 5RWdoLKS0NjPLfcXPWseIr+Wi/PdasJrvsp+bSlhZ7PL53jK4wvv6S1XdfsN/5au6axgbhYvbYJCh+RWSlLXv/cbpCiSXZ6FF13W/Fx6G0drDDsIeE1JrQL8gBjcZLGcVmbD9Xp0BFN+wOWxPc8vEk6Ycuu4pelZMsIc2+83W1J0e6X/ccPxqiUg8PhpJufktX6zX0extytsFJIHHQNnI12KB0JOLjm07aUTEbbb67YNdnloIY/70Reiex4sR+ACfB81QzNZc4/7KsTIWiO1DArwPa6XfADBGMogecme65d8urnxFNWKoefQ9sY9uFBFQt5PSy8Jq06cfezfsVsP8uKk6B8xI76pBBDYbt3ifqKGilY24vn/vHqXWr3PD43atB/ZpjtHiwBFb9pLrsVGDmttI4bXAsqt97HPk8O5C3qn005tZqMSIkFj5VwZAlDSG6pw5bxMgEPn+qFybf4LwskBH7p39lT1vJLoocd8V+oT3kqLE+/JojQASH+om1jCRRBWbf/okUzDZDk6EIOJEpQG1ZM4pP+9y01BfBtYJdDlPgVeRpYLu8DUh51Kxv6NtTN7LueRuKLsFAyIIsnJWTvBwvi/2KWA3eTLjIn0w0BjUB7VEvNkCs2+DC7PQdk0DPUWvVMPzqzeLasNiXvGpYRMIKB6y6kE4YNgFbEyPBk=
