language: node_js
node_js:
- '10'
deploy:
  provider: heroku
  app: koa-node-chat
  api_key:
    secure: LtXpOrq92+mneC53kHkENOTCnJSD68y0VM4N3u9m60GQr6PUouC5QvkQQ0c/sbGV/z3dKRSQZT7FvwNpRzUqpZkBZqqPd2lfppH/aYmaZ2aE/E2Jgfjyh5eQ1UzybDk+uQYoOXPKVt+v6fy3YCW0Ep1oZjtNY5eDyk+TrKh4EZWTeIpYqCf324GQJP0rDZILJ3xUJ5mZFD3S3PSkUvXJf7WnScw12M/G27lfNJLcJrcrzTC14Ko9DS92bIemAK42B/MzD+5C1nqEolhG9b2aFfKn8e+wmf3fFrJpf4OPBpefNHVWJxyRLbTcIKP5fLapE481GPM5g5yotH/zewLCyWXUSswOvImkoUxdEOvIxkXSze1iQOhW0Mst3pg1z4FPAcPjpse13rlKT5jFiDF1a1QN/XDDqpWtB3lOl//JF/yHYt9fyzL3ekuBedLynl1rJNVukDj0DFN8aginDB3ogi12z7wOazIq5H5ftakVbqExPEdHchj/kNELRfNhgCh+qNpNUOeh4AApP1jAxZKWiECKm4Rh07G2hZZ9siPKC8eQYEH1Yt9y/yzZcUUJEUQ2p/jDnsrWm1vy6yUeX5nAB7fUQvtMNrRQ5EbkskmAFbDxFwuUSoCLk2MSdU+K8YEr1UfEEVbsqTMh+kg8AvdZb5RxCtpqgEKdKY1riO9fHqM=
